
RAM_LEN = 64K
ROM_LEN = 512K

# include module specific includes
#~ INCLUDES += -I$(RIOTCPU)/atmega_common/include \
#~             -isystem$(RIOTCPU)/atmega_common/avr_libc_extra/include \
#~             -isystem$(RIOTCPU)/atmega_common/avr_libc_extra/include/vendor

#~ PSEUDOMODULES += atmega_pcint
#~ PSEUDOMODULES += atmega_pcint%

#~ include $(RIOTMAKE)/arch/atmega.inc.mk
include $(RIOTMAKE)/arch/avr32.inc.mk
